name: Publish and Release

on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  build-publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry lock
        poetry install

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI
      if: github.event_name == 'release'
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_PASSWORD
        poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD

    - name: Get the current version
      run: |
        VERSION=$(poetry version -s)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create a new release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag the commit
      if: github.event_name == 'push'
      run: |
        git tag "v$VERSION"
        git push origin "v$VERSION"
