name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry lock
        poetry install

    - name: Build the package
      run: poetry build

    - name: Get the current version
      run: |
        VERSION=$(poetry version -s)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Check if tag exists and create a new one
      run: |
        VERSION=$(poetry version -s)
        git fetch --tags
        if git tag -l | grep -q "v$VERSION"; then
          echo "Tag v$VERSION already exists, incrementing version"
          VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print $0}')
        fi
        git tag "v$VERSION"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/pavelixo/krieg.git
        git push origin "v$VERSION"

    - name: Create a new release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Publish to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_PASSWORD
        poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
